### PR TITLE
Adding safeUrl to bitbucket error messages

### PR DESCRIPTION
**Pull request by nathagey**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [x] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
Adding `safeUrl` to bitbucket error messages

### CODE REVIEW

**Comment by job13er** [comment]
Looks good, but you'll probably need to update this as well: https://github.com/ciena-blueplanet/pr-bumper/blob/master/tests/vcs/bitbucket-spec.js#L172

**Comment by job13er** [comment]
Hmmm, how did the that test pass... I must be missing something.

**Comment by nathagey** [comment]
That is confusing, let me check the test...

**Comment by nathagey** [comment]
The `to.be.eql` is not checking the error message, `to.be.equal` checks message.

**Comment by job13er** [comment]
That's odd, `.to.be.eql()` should be the same as `to.be.deep.equal()`:
http://chaijs.com/api/bdd/#method_eql

**Comment by job13er** [comment]
`.to.be.equal()` would only check for `===` so it'd fail if you're not pointing at the same memory reference.

**Comment by nathagey** [comment]
^ yep, my bad

**Comment by job13er** [comment]
👍

**Pull request merged**
