### PR TITLE
Add support for #none# version bump option

### LINKED ISSUE #49: [Discussion] Should there be a `#none#` directive?
Not sure of the actual keyword, but I was wondering if it would be a good idea to have support for a directive that passes the validation, but does not cause a version bump.

The rationale behind this is that sometimes there may be some changes to a package that result in no code change at all (files that are never pushed to an npm registry). An example would be changes to documentation files that are `.npmignore`d. Or changes to the `.travis.yml` file.

Normally I would just issue a `#patch#` change, but this is somewhat problematic when integrating with dependency updating like https://greenkeeper.io or https://gemnasium.com as they will report that an update needs to be made, _despite the package having no relevant changes_.

I'm on the fence with what is the right answer, so interested to see what others think.

### PR DESCRIPTION
**Pull request by sandersky**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #patch# - backwards-compatible bug fix
 - [x] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

resolves #49 

# CHANGELOG

* **Added** support for new `#none#` scope to support pull requests that do not bump the version resolving [#49](https://github.com/ciena-blueplanet/pr-bumper/issues/49) and [#40](https://github.com/ciena-blueplanet/pr-bumper/issues/40) (with the use of `tags: true` in `.travis.yml`)

### CODE REVIEW

**Comment by sandersky** [comment]
@job13er I'm not sure if you have a way to truly test this before it is merged or not but the changes looked pretty straightforward to me.

**Comment by job13er** [comment]
Have you given any thought to how to prevent the publish of packages which get the `#none#` directive? Not taking the time to figure out how that would work is what has kept me from implementing this thus far. I didn't want to support the option without understanding how it can be used.

**Comment by sandersky** [comment]
@job13er valid point. It actually won't publish as npm won't let you publish the same version twice. However every time you leverage `#none#` you'll get a failed merge build which isn't ideal. I'll give this some more thought.

**Comment by sandersky** [comment]
@job13er I see Travis CI's npm deploy allows you to set `tags: true` to only deploy on tagged commits. I've updated this PR to not add a tag or append to the CHANGELOG when the scope is `#none#`. Unless I'm missing something I think this will handle it. We just need to make sure our repositories that rely on `pr-bumper` set `tags: true` in their `.travis.yml`.

**Comment by sandersky** [comment]
Here is the Travis documentation on the `tags` option btw https://docs.travis-ci.com/user/deployment/npm/#What-to-release

**Comment by sandersky** [comment]
I've verified this change works in [this pull request](https://github.com/ciena-blueplanet/bunsen-core/pull/68) which uses my fork of `pr-bumper`. When using `#none#` it doesn't complain if the changelog section is missing and upon merging does not try to publish so I still get a green build (leverage the `tags: true` option in my Travis config).

screen shot 2017-02-08 at 5 27 15 pm

**Comment by job13er** [comment]
Sweet! I knew there was a tags option, but I was thinking it was deciding what to build, not what to deploy. We don't wanna re-run the build on those tags, but we do want to publish. Excellent find.

**Comment by sandersky** [comment]
Verified it again after my last commits https://github.com/ciena-blueplanet/bunsen-core/pull/69

**Comment by job13er** [comment]
:+1:

**Comment by job13er** [comment]
Oh no, I just realized something, shouldn't have merged this. Did you confirm that you can actually deploy when using something other than `#none#` with this. I have a bad suspicion that we're not building the tagged commit and so it'll never publish. B/c the commit being built isn't the `pr-bumper` tagged commit, it's the one previous. By setting the `tags: true` I think we may end up double-bumping:

PR Merge commit builds (not tagged, not deployed)
pr-bumper bump commit builds (is tagged, is deployed), possibly creates another pr-bumper bump commit.

We'll find out as the merge for this PR builds how it actually works. I think that either 
a) It won't publish at all
or
b) it'll publish too many times

Hopefully I'm wrong

**Comment by job13er** [comment]
So, looks like it was a) that is what happend:

screen shot 2017-02-09 at 4 48 05 am

**Comment by job13er** [comment]
So, because we have the actual bump as a `before_deploy` and `deploy` isn't happening except on a `tag` `pr-bumper` is never trying to bump :(

**Pull request merged**
